### ISSUE TITLE
TODO: convert_mod

### ISSUE THREAD

**Issue by superjohan** [superjohan/wonderswan-tools#6]
- [ ] Implement optional interpolation for waveforms
- [ ] Include necessary data in header
- [ ] Output bitmask to signal which effects are used
- [ ] Output padded 64k binary with player and songdata
- [ ] s3m support
