### ISSUE TITLE
TODO: convert_tiles

### ISSUE THREAD

**Issue by superjohan** [superjohan/wonderswan-tools#7]
- [x] make minimizing optional
- [x] implement flipped tiles
- [ ] support for multiple palettes
- [ ] support for splitting image into two layers, for more unique colors per tile
- [ ] support for PNGs with indexed palettes (either mandatory or optional)
- [ ] support for linear non-tiled output
